#!/usr/bin/env python3
"""Dead Drop Mailer Sendmail Replacement
Copyright (C) 2020 Frank Abelbeck <frank.abelbeck@googlemail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

#
# Modules, register of used objects and functions()
#
import datetime # datetime.now(), timezone.utc
import email.parser # BytesParser
import email.policy # SMTP
import getpass  # getuser()
import os.path # exists()
import platform # node()
import socket   # AF_INET, SOCK_DGRAM, socket
import sys      # argv, exit(), stdin
import syslog   # LOG_ALERT, LOG_CRIT, LOG_DEBUG, LOG_EMERG, LOG_ERR, LOG_INFO,
                # LOG_MAIL, LOG_NOTICE, LOG_WARNING, openlog(), syslog(), 

#
# hard-wired: pathes according to the filesystem hierarchy; listening on localhost
#
PATH_SOCKET = "/run/ddmailerd.socket"

# look-up table for print() version of mylog
LUTPRIO = {
	syslog.LOG_EMERG:   "EMRG",
	syslog.LOG_ALERT:   "ALRT",
	syslog.LOG_CRIT:    "CRIT",
	syslog.LOG_ERR:     "ERR ",
	syslog.LOG_WARNING: "WARN",
	syslog.LOG_NOTICE:  "NOTE",
	syslog.LOG_INFO:    "INFO",
	syslog.LOG_DEBUG:   "DBUG",
}

def mylog(priority=syslog.LOG_INFO,msg=""):
	#syslog.syslog(priority,msg)
	try:
		print("[{}] {}".format(LUTPRIO[priority],msg))
	except KeyError:
		print(msg)

#
# main routine
#
if __name__ == "__main__":
	hostname = platform.node()
	syslog.openlog(ident="DDMailer sendmail",logoption=0,facility=syslog.LOG_MAIL)
	
	# process commandline arguments
	# sys.argv[0] is the program file name
	# get all positional arguments (i.e. not starting with -)
	# these are the recipients; strip any @hostname as it is rewritten anyway
	recipients = []
	subject = ""
	for arg in sys.argv[1:]:
		if arg.startswith("--subject="):
			# convenience function: accept subject argument
			subject = arg[10:]
		elif arg == "--help":
			print("""Usage: sendmail [--help|--subject SUBJECT|RECIPIENT]...

Reads stdin until it encounters EOF or a line with a single dot.
Creates an e-mail message from the input and sends it to the DDMailer daemon.

Arguments:
   --help: display this help.
   --subject=SUBJECT: set the e-mail's subject to SUBJECT; overrides Subject
                      lines in the message text.
   RECIPIENT: one or more recipients of the message; overrides To lines in the
              message text; if no recipients given or no 

Examples:
   echo "Test" | sendmail info --subject "Test mail"
   myCommandProducingOutput | sendmail info
""")
			sys.exit(0)
		elif arg[0] != "-":
			# only process non-positional arguments, i.e. not starting with a dash
			if "@" not in arg: arg = arg + "@" + hostname
			recipients.append(arg)
	
	# read message from stdin until EOF or a line with a single dot.
	# read directly from buffer in order to obtain bytes
	messageBytes = b""
	for line in sys.stdin.buffer:
		if line == b".\n": break
		messageBytes = messageBytes + line
	parser = email.parser.BytesParser(policy=email.policy.SMTP)
	message = parser.parsebytes(messageBytes)
	
	# 2020-12-21: tuned behaviour to match cronie's mailing behaviour
	#  - recipients passed as arguments replace any To field in the message
	#  - if no recipients were passed as arguments, check that To is populated
	#  - if neither arguments were passed nor To is populated: bail out
	if len(recipients) == 0:
		if "To" not in message:
			# no recipients: exit
			mylog(syslog.LOG_WARNING,"No recipients given")
			sys.exit(1)
		# otherwise: To defined, proceed
	else:
		# use recipients passed as arguments
		del message["To"]
		message["To"] = ", ".join(recipients)
	
	# construct message by rewriting To, From and Date
	del message["From"]
	message["From"] = getpass.getuser().partition("@")[0] + "@" + platform.node()
	
	now = datetime.datetime.now(datetime.timezone.utc)
	del message["Date"]
	message["Date"] = now
	
	# 2021-01-02: add subject if passed as argument
	if len(subject) > 0:
		del message["Subject"]
		message["Subject"] = subject
	
	# send message to daemon
	try:
		with socket.socket(family=socket.AF_UNIX,type=socket.SOCK_STREAM) as usock:
			try:
				usock.connect(PATH_SOCKET)
				usock.sendall(message.as_bytes(policy=email.policy.SMTP))
			except OSError as e:
				mylog(syslog.LOG_ERR,"Message not sent ({})".format(e))
	except OSError as e:
		mylog(syslog.LOG_ERR,"Could not open UNIX socket ({})".format(e))
